### PR TITLE
Multi-stage dockerfile and Makefile

### PR DESCRIPTION
**Pull request by ahshabbir**
In the PR:

1. Added a multi-stage docker file. This should drastically reduce the size of the docker image, allowing for a smaller attack surface for bugs.
2. Added a Makefile to make it easy to build the API with and without docker, as well as adding linter checks.
3. Fixed the issues pointed out by the linter in our code.
4. Documented building and testing in docs/index.md (please let me know if this is the right place, or if I should change it)

### CODE REVIEW

**Comment by dlaunikitis** [comment]
`Step 8/13 : COPY go.mod go.sum server.go .
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1`

@ahshabbir Got this while building the docker file for the Google Cloud Artifact Repository

**Comment by ahshabbir** [comment]
> `Step 8/13 : COPY go.mod go.sum server.go . When using COPY with more than one source file, the destination must be a directory and end with a / ERROR ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1`
> 
> @ahshabbir Got this while building the docker file for the Google Cloud Artifact Repository

Fixed in latest commit, added the trailing slash

**Review by dlaunikitis — DISMISSED** [review]
Everything looks good on the engineering side! @AdamMcAdamson still needs to review the API specific code, but overall this is a good mix of improvements and additions to the API. Thanks for doing research into this and working towards an eventual API testing solution

**Review by AdamMcAdamson — DISMISSED** [review]
Looks great!

**Review by dlaunikitis — APPROVED** [review]

**Pull request merged**
