### PR TITLE
Exam Schema Changes

### PR DESCRIPTION
**Pull request by AdamMcAdamson**
Here are my proposed changes to the exam schema. Please let me know what you think, especially with the new Credit type.

### CODE REVIEW

**Review by jmyrick02 — APPROVED** [review]
Seems to handle the various edge cases well and is well-organized imo

**Comment by hochladen** [comment]
I like it, though I think you meant for the type of the `outcome:` property to be `Array<Array<ObjectId|Credit>>`, not `Array<Array<ObjectId>>`. Other than that, LGTM!

**Comment by AdamMcAdamson** [comment]
I ended up adding an ObjectId to Credit, so ObjectId is sufficient here. In the long term I don't know how it'll pan out, but removing it is easier than adding it in retroactively.

**Comment by hochladen** [comment]
We would need to push the credit objects to MongoDB for them having an ObjectID to make sense, but if that's the route you would like to take I'm not immediately opposed. 

I also know you brought up earlier that you weren't sure how we wanted to go about generating ObjectIDs for the exams, to which I'd say to just let Mongo generate them with `new mongoose.Types.ObjectId()` as is being done for the courses and sections. The the chance of IDs generated this way colliding is pretty much as low as with hashing, so it should not be a concern.

**Comment by AdamMcAdamson** [comment]
I have taken into consideration @hochladen's concerns, and have addressed another edge case for exam credits by generalizing credits into categories specified on site, since the nuances of the credits are somewhat cloudy.

**Review by dlaunikitis — APPROVED** [review]

**Pull request merged**
