### PR TITLE
Add Exam Data

### PR DESCRIPTION
**Pull request by AdamMcAdamson**
This is the resulting data from scrapping from the UT Dallas Exam sites for IP, AP, CLEP, and ALEKS, per #66.

This will need to be incorporated to the database deployments as seen fit.

This is mostly done by hand as I haven't had internet access to develop and debug the scraper. I hope to have that finished before 3/28/2022, but depending on our priorities may have to push that further down the road.

### CODE REVIEW

**Review by TrystonMinsquero — APPROVED** [review]

**Review by jmyrick02 — CHANGES_REQUESTED** [review]
This is great work but regrettably it does not seem to follow our current schema decisions. The current schema states that the `yields` dictionary should map integers to an Array of ObjectIds (which would point to the course object that credit would be received for). This data maps strings to Arrays of objects that are undefined in our current schema. As a remark, the way I envisioned handling the 3 free SCH electives is to make a 3 credit SCH course in the course database. Other approaches to the `Exam` schema by changing the schema are welcome with input from others on the team.

**Comment by CharlieMahana** [comment]
What is the status on refactoring the data obtained by the exam scraper per @jmyrick02's observations?

**Comment by AdamMcAdamson** [comment]
I think I'm not entirely caught up on how we are establishing the Course ObjectIds.

I've been assuming they will be generated. If that is the case, then we will have to employ a separate script to build the associations between courses as outlined here (with prefix/number combinations) and their respective ObjectIds in the database, as they will be deployment/cluster specific.

If this is not the case, can you point me to the strings we are basing the ObjectIds off of?

Even so, I think this data should exist separate from the implementation specific details on that level, as this is still in active development.

**Comment by hochladen** [comment]
The course ObjectIDs are generated by the scraper upon scraping the course data, after which the course data is pushed to MongoDB. In order to link courses to their IDs from other things, then, you'll need to poll MongoDB for the courses and find the IDs of matching courses.

I hope this helps to clarify.

**Comment by AdamMcAdamson** [comment]
Yes, this is what I thought. I will assume that the scraper data will be available as seen on @hochladen's fork. 

I will create a script to build those associations, but I still think this data should exist independently, as re-scraping the data will break the associations, requiring the exam data to be reassembled into this form in order to repair the associations.

There are a few other edge cases not properly represented with the Exam schema/data, as with AP Physics where for "Physics Majors: Credit for 2326 + 2126 is applied only if PHYS 3416 is passed with a grade of C or higher; otherwise you earn 4 SCH of free electives". All are AP credit specific, and are outlined by the endnotes on the [AP Credit website](https://oue.utdallas.edu/undergraduate-advising/ap-credit).

**Comment by AdamMcAdamson** [comment]
That mostly looks good to me. 
I do however think that since SCH elective credits often have prefix/school associated with them, a number alone will not suffice. Either something like @jmyrick02's solution, or creating a new type, is probably the way to go.

**Comment by hochladen** [comment]
Ah, that is a good point. I think just making a new type would be cleaner than making some sort of psuedo-course for representing them, but I'm open.

**Review by dlaunikitis — APPROVED** [review]

**Pull request merged**
